from pathlib import Path
import re
import shutil

import pytest

from yupp.pp import yup
from tests.conftest import REPO_ROOT


EXAMPLES = REPO_ROOT / "eg"


def normalize_generated_header(text):
    text = re.sub(r"generated by yupp \S+", "generated by yupp <VERSION>", text)
    return re.sub(r" at \d{4}-\d{2}-\d{2} \d{2}:\d{2}", " at <DATETIME>", text)


@pytest.mark.integration
@pytest.mark.parametrize(
    "source_name,golden_name,config_name",
    [
        ("hello.yu-c", "hello.c", None),
        ("argv.yu-c", "argv.c", None),
        ("dict.yu-py", "dict.py", "dict.yuconfig"),
        ("unfold.yu-c", "unfold.c", None),
        ("switch.py", "switch.yugen.py", None),
    ],
)
def test_representative_example_matches_checked_in_golden(
    source_name, golden_name, config_name, tmp_path, monkeypatch
):
    source = tmp_path / source_name
    shutil.copy2(EXAMPLES / source_name, source)
    if config_name:
        shutil.copy2(EXAMPLES / config_name, tmp_path / config_name)
    monkeypatch.chdir(tmp_path)

    status = yup.cli(["-q", "--no-read-only", str(source)])

    assert status == 0
    actual = normalize_generated_header((tmp_path / golden_name).read_text(encoding="utf8"))
    expected = normalize_generated_header((EXAMPLES / golden_name).read_text(encoding="utf8"))
    assert actual == expected


@pytest.mark.integration
def test_passage_example_generates_all_checked_in_outputs(tmp_path, monkeypatch):
    source = tmp_path / "passage.yu-c"
    shutil.copy2(EXAMPLES / "passage.yu-c", source)
    monkeypatch.chdir(tmp_path)

    status = yup.cli(["-q", "--no-read-only", str(source)])

    assert status == 0
    for name in ("passage-a.c", "passage-b.c", "passage-c.c"):
        actual = normalize_generated_header((tmp_path / name).read_text(encoding="utf8"))
        expected = normalize_generated_header((EXAMPLES / name).read_text(encoding="utf8"))
        assert actual == expected


@pytest.mark.integration
def test_sequential_files_do_not_share_evaluator_bindings(tmp_path, monkeypatch):
    first = tmp_path / "first.yu-c"
    second = tmp_path / "second.yu-c"
    first.write_text("($set cross_file 17)FIRST=($cross_file)", encoding="utf8")
    second.write_text("SECOND=($cross_file)", encoding="utf8")
    monkeypatch.chdir(tmp_path)

    status = yup.cli(["-q", "--no-read-only", str(first), str(second)])

    assert status == 0
    assert (tmp_path / "first.c").read_text(encoding="utf8") == "FIRST=17\n"
    assert (tmp_path / "second.c").read_text(encoding="utf8") == "SECOND=cross_file\n"


def test_example_checks_never_target_the_repository_outputs():
    """A guardrail for the characterization suite itself."""
    assert all(path.is_file() for path in (EXAMPLES / "hello.c", EXAMPLES / "passage-a.c"))
