#! /usr/bin/env python

#  coro.yugen.py was generated by yupp 1.2b1
#  out of coro.py

from __future__ import print_function

from future.builtins import next

CO_READY = 0
CO_WAIT  = 1
CO_YIELD = 2
CO_END   = 3
CO_SKIP  = 4

c = False

def coro_A():
    while True:
        print( 'A' )
        yield CO_YIELD

def coro_B():
    global c

    for i in range( 5 ):
        print( 'B' )
        if i & 1:
            c = True
        yield CO_YIELD

    while True: yield CO_END

def coro_C():
    global c

    while True:
        while not ( c ): yield CO_WAIT
        print( 'C' )
        c = False

if __name__ == '__main__':
    A = coro_A()
    B = coro_B()
    C = coro_C()

    while True:
        next( A )
        if not ((  next( B ) ) < CO_END ):
            break
        next( C )
        print()
