
#  dict.py was generated by yupp 1.2b1
#  out of dict.yu-py

from __future__ import print_function

var_string = "montreal"
var_float = 19.96
var_int = 6

if __name__ == '__main__':
    print( "var_string = %s" % ( var_string ))
    print( "var_float = %.2f" % ( var_float ))
    print( "var_int = %d" % ( var_int ))

    var_int += 2
