
#  dict.py was generated by yup.py (yupp) 0.9b7
#  out of dict.yu-py at 2016-09-23 18:05

var_string = "montreal"
var_float = 19.96
var_int = 6

if __name__ == '__main__':
    print "var_string = %s" % ( var_string )
    print "var_float = %.2f" % ( var_float )
    print "var_int = %d" % ( var_int )

    var_int += 2
