/*  dict.c was generated by yup.py (yupp) 0.8b8
    out of dict.yu-c at 2015-08-07 20:18
 */

#include <stdio.h>

int main( void )
{
	/* Declare variables */
	char app[ 5 ] = "yupp";
	float release = 0.8;
	char pre = 'b';
	unsigned int number = 8;

	printf( "dict.yu-c\n" );

	/* Print variables */
	printf( "%s ", app );
	printf( "%.1f", release );
	printf( "%c", pre );
	printf( "%d", number );

	return 0;
}
