/*  hello.c was generated by yup.py (yupp) 0.8b8
    out of hello.yu-c at 2015-08-03 17:20
 */

#include <stdio.h>

int main( void )
{
	/* Declare variables */
	float Pi = 3.14159265359;
	char ch = '~';
	float Zu = 3.14159292035;

	printf( "Hello world!\n" );

	/* Print variables */
	printf( "%f", Pi );
	printf( "%c", ch );
	printf( "%f", Zu );

	return 0;
}
