/*  unfold.c was generated by yupp 1.2b1
    out of unfold.yu-c
 */

#include <stdio.h>

int main( void )
{
    printf( "Hello Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune!\n" );
    return 0;
}
