/*  unfold.c was generated by yup.py (yupp) 1.0b7
    out of unfold.yu-c 
 */

#include <stdio.h>

int main( void )
{
    printf( "Hello Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune!\n" );
    return 0;
}
