"""Scoped traceback source mapping for Python programs generated by yupp.

The implementation deliberately builds on the public :mod:`traceback` data
model.  It does not replace any stdlib traceback classes or functions.
"""

from dataclasses import dataclass
import os
import sys
import traceback


@dataclass(frozen=True)
class _Mapping:
    generated: str
    shrink: int


_mappings = {}
_previous_hook = None
_installed = False


def _realpath(filename):
    return os.path.realpath(os.fspath(filename))


def _mapped_line(lineno, shrink):
    return max(1, lineno - shrink + 1)


def _remap_frame(frame):
    mapping = _mappings.get(_realpath(frame.filename))
    if mapping is None:
        return frame, False

    end_lineno = frame.end_lineno
    if end_lineno is not None:
        end_lineno = _mapped_line(end_lineno, mapping.shrink)

    # Constructing a new summary asks linecache to resolve the generated file
    # through the supported FrameSummary interface on Python 3.11+.
    mapped = traceback.FrameSummary(
        mapping.generated,
        _mapped_line(frame.lineno, mapping.shrink),
        frame.name,
        lookup_line=True,
        locals=frame.locals,
        line=None,
        end_lineno=end_lineno,
        colno=frame.colno,
        end_colno=frame.end_colno,
    )
    return mapped, True


def _remap_exception(exception):
    """Remap *exception* and its public chain/group tree in place."""
    mapped_count = 0
    frames = []
    for frame in exception.stack:
        mapped, changed = _remap_frame(frame)
        frames.append(mapped)
        mapped_count += int(changed)
    if mapped_count:
        exception.stack = traceback.StackSummary.from_list(frames)

    if exception.__cause__ is not None:
        mapped_count += _remap_exception(exception.__cause__)
    if exception.__context__ is not None:
        mapped_count += _remap_exception(exception.__context__)
    if exception.exceptions is not None:
        for nested in exception.exceptions:
            mapped_count += _remap_exception(nested)
    return mapped_count


def _excepthook(exc_type, value, tb):
    previous = _previous_hook or sys.__excepthook__
    if issubclass(exc_type, KeyboardInterrupt):
        previous(exc_type, value, tb)
        return

    # On Python 3.14 eager line lookup would reopen the yupp-coded source and
    # recursively invoke the codec with linecache's partial input.  Defer it;
    # mapped frames below resolve lines from the generated artifact instead.
    formatted = traceback.TracebackException(
        exc_type, value, tb, lookup_lines=False
    )
    if not _remap_exception(formatted):
        previous(exc_type, value, tb)
        return
    formatted.print(file=sys.stderr)


def install_mapping(source_filename, generated_filename, shrink):
    """Register one source mapping and install the hook once.

    ``shrink`` is the number of source header lines consumed by the macro
    preprocessor.  Generated line numbers follow yupp's historical
    ``line - shrink + 1`` mapping rule.
    """
    global _installed, _previous_hook

    _mappings[_realpath(source_filename)] = _Mapping(
        _realpath(generated_filename), int(shrink)
    )
    if not _installed:
        _previous_hook = sys.excepthook
        sys.excepthook = _excepthook
        _installed = True


def _reset_for_tests():
    """Restore module state without disturbing a subsequently installed hook."""
    global _installed, _previous_hook

    if _installed and sys.excepthook is _excepthook:
        sys.excepthook = _previous_hook or sys.__excepthook__
    _mappings.clear()
    _previous_hook = None
    _installed = False


__all__ = ["install_mapping"]
