
/*  main.c was generated by yup.py (yupp) 1.0c3
    out of main.yu-c 
 *//**
 *  \file  main.c (main.yu-c)
 *  \brief  The example of an application.
 *  \author  Vitaly Kravtsov (in4lio@gmail.com)
 *  \copyright  See the LICENSE file.
 */

#include <stdio.h>
#include "co.h"

/**
 *  \brief Initialize all coroutines.
 */
static void coro_init( void )
{
	CORO_CONTEXT_INIT( A );
	A_alive = A_init();
	CORO_CONTEXT_INIT( B );
	B_alive = B_init();
	CORO_CONTEXT_INIT( C );
	C_alive = C_init();

}

/**
 *  \brief Uninitialize all coroutines.
 */
static void coro_uninit( void )
{
	A_uninit();
	B_uninit();
	C_uninit();

}

/**
 *  \brief Call coroutines according to dictionary.
 */
static int coro_schedule( void )
{
	if ( CORO_ALIVE( A_alive ) ) A_alive = CORO_CALL( A );
	if ( CORO_ALIVE( B_alive ) ) B_alive = CORO_CALL( B );
	if ( CORO_ALIVE( C_alive ) ) C_alive = CORO_CALL( C );

	return ( 0
	|| CORO_ALIVE( A_alive )
	|| CORO_ALIVE( B_alive )
	|| CORO_ALIVE( C_alive )

	);
}

int main( void )
{
	coro_init();
	for ( ; ; ) {
		if ( coro_schedule() == 0 ) break;
	}
	coro_uninit();

	return 0;
}
